apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-component-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-sample-component-name
    app.kubernetes.io/part-of: go-application-sample
  name: go-component-sample
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: go-component-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: go-component-sample
    spec:
      containers:
      - image: docker.io/mm4eche/foobar:go-srv
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
